Implement purchase logger
kaya-ken/Server pull request #8
Opened 2020-02-11 18:15 UTC by NB29979

購入履歴を記録するロガーの実装
https://github.com/kaya-ken/Server/issues/3

2020-02-12 04:32 UTC, kaya-ken reviewed
プロキシが書かれた状態でgithubにあげてよろしいのか疑問点

2020-02-12 05:00 UTC, NB29979 commented
Proxyの件はMyProxyなどで対応

2020-02-12 08:32 UTC, yuki1222yuki approved these changes
天才すぎる。

2020-02-12 13:50 UTC, NB29979 commented
@kaya-ken 対応しましたので確認お願いします

2020-02-23 07:44 UTC, kaya-ken requested changes
MyProxyへの変更を確認しました．

2020-02-23 07:47 UTC, kaya-ken approved these changes
間違えてRequest changesしてました

2020-02-23 07:47 UTC, merged